---
title: "NONLINEAR REGRESSION"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document: default
---

# Download the data
```{r}
#Source files are here
#setwd('D:/ML')

##Features scaling is included in the packages we will work with

#Download the files
f_train <- read.csv2('flats_train.csv', header = TRUE, encoding = 'UNICOD')
f_test <- read.csv2('flats_test.csv', header = TRUE, encoding = 'UNICOD')
```

# Decision Tree Regression

## Fitting
```{r}
# install.packages('rpart')
library(rpart)
model_dt <- rpart(price ~ m2, f_train, control = rpart.control(minsplit = 10))
plot(model_dt)
text(model_dt, pos = 1, cex = 0.75, col = 1, font = 1)
```

## Predicting
```{r}
p_dt <- predict(model_dt, f_test)

train_mse_dt <- sum((f_train$price-predict(model_dt, f_train))^2)/length(f_train$price)
test_mse_dt <- sum((f_test$price-p_dt)^2)/length(p_dt)

train_mse_dt
test_mse_dt
```

## Visualising
```{r}
library(ggplot2)
x_grid <- seq(min(f_train$m2), max(f_train$m2), 0.01)
ggplot() +
  geom_point(aes(f_train$m2, f_train$price),colour = 'red') +
  geom_point(aes(f_test$m2, f_test$price),colour = 'dark green') +
  geom_line(aes(x_grid, predict(model_dt, data.frame(m2 = x_grid))),colour = 'blue') +
  ggtitle('Price vs m2') +
  xlab('m2') +
  ylab('price')
```

# Random forest

## Fitting
```{r}
# install.packages('randomForest')
library(randomForest)
set.seed(1234)
model_rf = randomForest(x = f_train['m2'],
                         y = f_train$price,
                         ntree = 50)
```

## Predicting
```{r}
p_rf <- predict(model_rf, f_test)

train_mse_rf <- sum((f_train$price-predict(model_rf, f_train))^2)/length(f_train$price)
test_mse_rf <- sum((f_test$price-p_rf)^2)/length(p_rf)

train_mse_rf
test_mse_rf
```

## Visualising
```{r}
ggplot() +
  geom_point(aes(f_train$m2, f_train$price),colour = 'red') +
  geom_point(aes(f_test$m2, f_test$price),colour = 'dark green') +
  geom_line(aes(x_grid, predict(model_rf, data.frame(m2 = x_grid))),colour = 'blue') +
  ggtitle('Price vs m2') +
  xlab('m2') +
  ylab('price')
```

# Saving results
```{r}
fit <- read.csv2('flats_fit.csv', header = TRUE, encoding = 'UNICOD')
fit$p_dt <- p_dt
fit$p_rf <- p_rf
head(fit)
write.csv2(fit[-1], file = "flats_fit.csv")
```