---
title: "K-Nearest Neighbors (K-NN)"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
#setwd('D:/ML')
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
```

# Features Scaling
```{r}
f <- f[,c('age','income','delays')]
sc <- scale(f[-3])
f$age <- sc[,c('age')]
f$income <- sc[,c('income')]
head (f)
```

# Splitting the scaled dataset into the TRAIN set and TEST set
```{r}
set.seed(123)
library(caTools)
split = sample.split(f$delays, SplitRatio = 2/3)
f_train = subset(f, split == TRUE)
f_test = subset(f, split == FALSE)
```

# Fitting & predicting
```{r}
library(class)
y = knn(train = f_train[,c('age','income')],
        test = f_test[,c('age','income')],
        cl = f_train[, 'delays'],
        k = 5,
        prob = TRUE)
```

## Confusion Matrix
```{r}
cm = table(f_test[, 'delays'], y == 'YES')
print(cm)
```

## Visualising the Test set results
```{r}
#install.packages("ElemStatLearn")
library(ElemStatLearn)
set = f_test
X1 = seq(min(set['age']) - 1, max(set['age']) + 1, by = 0.01)
X2 = seq(min(set['income']) - 1, max(set['income']) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('age', 'income')
y_grid = knn(train = f_train[,c('age','income')], test = grid_set, cl = f_train[, 'delays'], k = 5)
plot(set[, -3],
     main = 'KNN',
     xlab = 'Age', ylab = 'Income',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 'YES', 'tomato', 'springgreen3'))
points(set, pch = 21, bg = ifelse(set[, 3] == 'YES', 'red3', 'green4'))
```