---
title: "Hierarchical clustering"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
#setwd('D:/ML')
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
f <- f[, c('age', 'income')]
```

# Hierarchical clustering
```{r}
model_hc <- hclust(dist(f), method = "ward.D" )
plot(model_hc, main = paste('Dendrogram'))
```

## Fitting HC to the dataset
```{r}
y_hc <- cutree(model_hc, k = 3)
#cluster cores
aggregate(f,by=list(y_hc),FUN=mean)
```

## Plotting the dendrogram
```{r}
plot(model_hc, cex = 0.7, labels = FALSE)
rect.hclust(model_hc, k = 3, border = 2:5)
```

## Visualising the clusters
```{r}
library(cluster)
clusplot(f,
         y_hc,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels= 0,
         plotchar = FALSE,
         span = TRUE,
         main = paste('Clusters of customers'),
         xlab = 'Age',
         ylab = 'Income')
```