---
title: "Association Rules"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
library(dplyr)
set.seed(123)
#setwd('D:/ML')
#install.packages('arules')
library(arules)
f <- read.transactions ('mini-market.csv', sep = ',', rm.duplicates = TRUE)
summary(f)
itemFrequencyPlot(f, topN = 19)
```

# Eclat
```{r}
model_eclat = eclat(data = f, parameter = list(support = 0.017, minlen = 2))
# Visualising the results
inspect(sort(model_eclat, by = 'support')[1:10])
```

# Apriori
```{r}
model_ap = apriori(data = f, parameter = list(support = 0.01, confidence = 0.2))
# Visualising the results
inspect(sort(model_ap, by = 'lift')[1:10])
```

# Graph
```{r}
library(arulesViz)
plot(model_ap, measure = c("support", "confidence"), shading = "lift")
```

```{r}
plot(head(sort(model_ap, by = "support"), 30), method = "graph",
     control = list(nodeCol = rainbow(16), 
                    edgeCol = grey(.85), alpha = 1))
```