---
title: "NEUORAL NETWORKS FOR APPROXIMATION"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data and libraries
```{r}
library(dplyr)
library(nnet)
library(ggplot2)
library(knitr)
library (psych)
#Set Working Directory
#setwd('D:/ML')
#OR Choose your Directory in 'Files' and click on 'More' -> 'Set as Working Directory' #Download file to the table. Source file is 'flats.csv'
f <- read.csv2('flats.csv', header = TRUE, encoding = 'UNICOD')
describe(f)
```

## Missing data, fill n/a with average 
```{r}
f_fill <- f
##with average for integer vars 
f_fill$rooms <- ifelse(is.na(f$rooms),round(mean(f$rooms,na.rm = TRUE)),f$rooms)
##the most frequent for categorical vars
f_fill$type <- ifelse(is.na(f$type),which.max(table(f$type)),f$type)
f_fill$type <- as.factor(f_fill$type)
f <- f_fill
```

## Ejections (outside the three sigma).
```{r}
f_ej <- f
f_ej$price <- ifelse(f$price < mean(f$price)+sd(f$price)*3,f$price,mean(f$price)+sd(f$price)*3)
describe(f_ej$price)
f <- f_ej
```

## Factors as numeric
```{r}
f$location <- as.numeric(f$location)
f$condition <- as.numeric(f$condition)
f$type <- as.numeric(f$type)
```

## Features Scaling
```{r}
f_sc <- f
f_sc$price <- scale(f$price)
f_sc$rooms <- scale(f$rooms)
f_sc$m2 <- scale(f$m2)
head (f_sc)
```

## Splitting the scaled dataset into the TRAIN set and TEST set
```{r}
set.seed(123)
library(caTools)
split = sample.split(f_sc$price, SplitRatio = 0.8)
f_train = subset(f_sc, split == TRUE)
f_test = subset(f_sc, split == FALSE)
```

# Fitting the NN
```{r results='hide'}
set.seed(333)
ff_ap <- nnet(data = f_train, price ~ m2 + location + type, linout = TRUE ,size = 6, maxit = 10000)
library(graphics)
source(file = 'plot.nnet.R')
plot.nnet(ff_ap)
```

## Prediction
```{r}
p_ff_ap <- predict(ff_ap, f_test)

train_mse_ff_ap <- sum((f_train$price-predict(ff_ap, f_train))^2)/length(f_train$price)
test_mse_ff_ap <- sum((f_test$price-p_ff_ap)^2)/length(p_ff_ap)

train_mse_ff_ap
test_mse_ff_ap
```

## Visualising
```{r}
library(ggplot2)
ggplot() +
  geom_point(aes(f_train$m2, f_train$price),colour = 'red') +
  geom_point(aes(f_test$m2, f_test$price),colour = 'dark green') +
  geom_line(aes(f_test$m2, p_ff_ap),colour = 'blue') +
  ggtitle('Price vs m2') +
  xlab('m2') +
  ylab('price')
```

# Fit NN-2 
```{r  results='hide'}
library(neuralnet)

# fit neural network
set.seed(2)
nn = neuralnet(price ~ ., f_train, hidden = 3 , linear.output = T )

# plot neural network
plot(nn)
```

## Prediction
```{r}
p_nn <- predict(nn, f_test)

train_mse_nn <- sum((f_train$price-predict(nn, f_train))^2)/length(f_train$price)
test_mse_nn <- sum((f_test$price-p_nn)^2)/length(p_nn)

train_mse_nn
test_mse_nn
```

## Visualising
```{r}
library(ggplot2)
ggplot() +
  geom_point(aes(f_train$m2, f_train$price),colour = 'red') +
  geom_point(aes(f_test$m2, f_test$price),colour = 'dark green') +
  geom_line(aes(f_test$m2, p_nn),colour = 'blue') +
  ggtitle('Price vs m2') +
  xlab('m2') +
  ylab('price')
```