---
title: "Feature Extraction - LDA"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
#setwd('D:/ML')
f <- read.csv('Wine.csv', header = TRUE, encoding = 'UNICOD')
```

## Features Scaling
```{r}
f[-14] <- as.data.frame(scale(f[-14]))
```

## Splitting the dataset into the TRAIN set and TEST set
```{r}
set.seed(123)
library(caTools)
split = sample.split(f$Customer_Segment, SplitRatio = 2/3)
f_train = subset(f, split == TRUE)
f_test = subset(f, split == FALSE)
```

# Applying LDA
```{r}
library(MASS)
#It's a supervised algorithm. The number of variables (linear discriminants) is equal to the number of classes - 1
lda = lda(formula = Customer_Segment ~ ., data = f_train)
f_train = as.data.frame(predict(lda, f_train))
f_train = f_train[c(5, 6, 1)]
f_test = as.data.frame(predict(lda, f_test))
f_test = f_test[c(5, 6, 1)]
```

# Fitting SVM to the LDA-Training set
```{r}
# install.packages('e1071')
library(e1071)
classifier = svm(formula = class ~ .,
                 data = f_train,
                 type = 'C-classification',
                 kernel = 'linear')
```

## Predicting the Test set results
```{r}
y_pred = predict(classifier, newdata = f_test[-3])
```

## Making the Confusion Matrix
```{r}
cm = table(f_test[, 3], y_pred)
print(cm)
```

## Visualising the Test set results
```{r}
library(ElemStatLearn)
set = f_test
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('x.LD1', 'x.LD2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3], main = 'SVM (Test set)',
     xlab = 'LD1', ylab = 'LD2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 2, 'deepskyblue', ifelse(y_grid == 1, 'springgreen3', 'tomato')))
points(set, pch = 21, bg = ifelse(set[, 3] == 2, 'blue3', ifelse(set[, 3] == 1, 'green4', 'red3')))
```
