---
title: "XBoost"
output: word_document
---

# Download the data
```{r}
set.seed(123)
f_train <- read.csv2('bank_train.csv', header = TRUE, encoding = 'UNICOD')
f_test <- read.csv2('bank_test.csv', header = TRUE, encoding = 'UNICOD')
f_train <- f_train[-1]
f_test <- f_test[-1]
```

# Fitting XGBoost to the Training set
```{r}
# install.packages('xgboost')
library(xgboost)
class_xboost = xgboost(data = as.matrix(f_train[-8]), label = f_train$delays, nrounds = 10)
```

## Predicting the Test set results
```{r}
y_pred = predict(class_xboost, newdata = as.matrix(f_test[-8]))
y_pred = (y_pred >= 0.5)
```

## Making the Confusion Matrix
```{r}
cm = table(f_test[, 8], y_pred)
print(cm)
```

# Applying k-Fold Cross Validation
```{r}
# install.packages('caret')
library(caret)
folds = createFolds(f_train$delays, k = 10)
cv = lapply(folds, function(x) {
  train_fold = f_train[-x, ]
  test_fold = f_train[x, ]
  class_xboost = xgboost(data = as.matrix(train_fold[-8]), label = train_fold$delays, nrounds = 10)
  y_pred = predict(class_xboost, newdata = as.matrix(test_fold[-8]))
  y_pred = (y_pred >= 0.5)
  cm = table(test_fold[, 8], y_pred)
  accuracy = (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
  return(accuracy)
})
accuracy = mean(as.numeric(cv))
print(accuracy)
```
