---
title: "Support Vector Machine (SVM)"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
#setwd('D:/ML')
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
```

# Features Scaling
```{r}
f <- f[,c('age','income','delays')]
sc <- scale(f[-3])
f$age <- sc[,c('age')]
f$income <- sc[,c('income')]
f$delays <- as.numeric(as.factor(f$delays)) - 1
```

# Splitting the scaled dataset into the TRAIN set and TEST set
```{r}
set.seed(123)
library(caTools)
split = sample.split(f$delays, SplitRatio = 2/3)
f_train = subset(f, split == TRUE)
f_test = subset(f, split == FALSE)
```

# Fitting linear model
```{r}
# install.packages('e1071')
library(e1071)
class_svm_l = svm(delays ~ ., data = f_train, kernel = 'linear')
summary(class_svm_l)
```

# Predicting
```{r}
p <- predict(class_svm_l, f_test[, c('age','income')])
y <- ifelse(p > 0.5, 1, 0)
```

## Confusion Matrix
```{r}
cm = table(f_test[, 'delays'], y)
print(cm)
```

# Visualising the Test set results
```{r}
xgrid = expand.grid(age = f_test$age, income = f_test$income)
ygrid = predict(class_svm_l, xgrid)

#Finally, you plot the points and color them according to the decision boundary. You can see that the decision boundary is linear. You can put the data points in the plot as well to see where they lie.

plot(xgrid, col = as.numeric(ygrid), pch = 20, cex = .2)
points(f_test[, c('age','income')], col = as.factor(f_test$delays), pch = 19)
```

# Fitting RBF model
```{r}
# install.packages('e1071')
library(e1071)
class_svm_r = svm(delays ~ ., data = f_train, kernel = 'radial')
summary(class_svm_r)
```

# Predicting
```{r}
p <- predict(class_svm_r, f_test[, c('age','income')])
y <- ifelse(p > 0.5, 1, 0)
```

## Confusion Matrix
```{r}
cm = table(f_test[, 'delays'], y)
print(cm)
```

# Visualising the Test set results
```{r}
library(ggplot2)
set = f_test[,c('age','income','delays')]
X1 = seq(min(set['age']) - 1, max(set['age']) + 1, by = 0.01)
X2 = seq(min(set['income']) - 1, max(set['income']) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('age', 'income')
p_grid = predict(class_svm_r, grid_set)
y_grid <- ifelse(p_grid > 0.5, 1, 0)
plot(set[, -3],
     main = 'SVM',
     xlab = 'Age', ylab = 'Income',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'tomato', 'springgreen3'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'red3', 'green4'))
```
