---
title: "K-Means"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
head(f)
```

## Factors as numeric
```{r}
f <- f[,-1] #exclude ID column
f$sex <- as.numeric(as.factor(f$sex))-1
f$married <- as.numeric(as.factor(f$married))-1
f$car <- as.numeric(as.factor(f$car))-1
f$mortgage <- as.numeric(as.factor(f$mortgage))-1
f$delays <- as.numeric(as.factor(f$delays))-1
head (f)
```

## Historgram for each attribute
```{r}
library(tidyr)
library(ggplot2)
f %>% 
  gather(Attributes, value, 1:8) %>% 
  ggplot(aes(x=value)) +
  geom_histogram(fill = "lightblue2", color = "black") + 
  facet_wrap(~Attributes, scales = "free_x") +
  labs(x = "Value", y = "Frequency")
```

## Correlation
```{r}
library(corrplot)
corrplot(cor(f), type = "upper", method = "ellipse", tl.cex = 0.9)
```

# NbCLust
```{r}
library(factoextra)
library(NbClust)

res.nbclust <- NbClust(f, distance = "euclidean",
                  min.nc = 2, max.nc = 10, 
                  method = "complete", index ="all")
fviz_nbclust(res.nbclust) + theme_minimal() + ggtitle("NbClust's optimal number of clusters")

# Elbow method
# The sum of squares at each number of clusters is calculated and graphed, and the user looks for a change of slope from steep to shallow (an elbow) to determine the optimal number of clusters.
fviz_nbclust(f, kmeans, method = "wss") +
    geom_vline(xintercept = 3, linetype = 2)+
  labs(subtitle = "Elbow method")

# Silhouette method
# The optimal number of clusters k is the one that maximize the average silhouette over a range of possible values for k.
fviz_nbclust(f, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")

# Gap statistic
# The gap statistic compares the total within intra-cluster variation for different values of k with their expected values under null reference distribution of the data. The estimate of the optimal clusters will be value that maximize the gap statistic. This means that the clustering structure is far away from the random uniform distribution of points.
fviz_nbclust(f, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
```

## Clustree
```{r}
library(clustree)
library(dplyr)
tmp <- NULL
for (k in 1:4){
  tmp[k] <- kmeans(f, k, nstart = 30)
}
df <- data.frame(tmp)
# add a prefix to the column names
colnames(df) <- seq(1:4
                    )
colnames(df) <- paste0("k",colnames(df))
# get individual PCA
df.pca <- prcomp(df, center = TRUE, scale. = FALSE)
ind.coord <- df.pca$x
ind.coord <- ind.coord[,1:2]
df <- bind_cols(as.data.frame(df), as.data.frame(ind.coord))
clustree(df, prefix = "k")
```

# Fitting K-Means to the dataset
```{r}
set.seed(29)
model_km = kmeans(f, 2)
#cluster cores
y_km = model_km$cluster
aggregate(f,by=list(y_km),FUN=mean)
```

# Visualising the clusters
```{r}
library(cluster)
clusplot(f[,c('age','income')],
         y_km,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels= 0,
         plotchar = FALSE,
         span = TRUE,
         main = paste('Clusters of customers'),
         xlab = 'Age',
         ylab = 'Income')
```

# Comparing to HC
```{r}
library(clusteval)
cluster_similarity(y_hc,y_km)
```