---
title: "Kohonen maps"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data
```{r}
set.seed(123)
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
head (f)
```

## Factors as numeric
```{r}
f <- f[,-1] #exclude ID column
f$sex <- as.numeric(as.factor(f$sex))-1
f$married <- as.numeric(as.factor(f$married))-1
f$car <- as.numeric(as.factor(f$car))-1
f$mortgage <- as.numeric(as.factor(f$mortgage))-1
f$delays <- as.numeric(as.factor(f$delays))-1
head (f)
```

# Features Scaling
```{r}
mage <- mean(f$age)
sage <- sd(f$age)
mincome <- mean(f$income)
sincome <- sd(f$income)
mchildren <- mean(f$children)
schildren <- sd(f$children)

f$age <- (f$age-mage)/sage
f$income <- (f$income-mincome)/sincome
f$children <- (f$children-mchildren)/schildren

f_matrix <- as.matrix(f)

head (f)
```

# Fitting the NN
```{r}
set.seed(123)
library(kohonen)
som_grid <- somgrid(xdim = 10, ydim = 6, topo = "hexagonal") 
som_model <- som(f_matrix, grid = som_grid, rlen = 1000,
                 alpha = c(0.05,0.01), keep.data = TRUE)
plot(som_model, type = "changes")
```

## Visualization
```{r}
#Palette
coolBlueHotRed <- function(n, alpha = 1) {
    rainbow(n, end = 4/6, alpha = alpha)[n:1] 
}
par(mfrow = c(1, 2))
#Number of objects at sells
plot(som_model, type = "counts", palette.name = coolBlueHotRed)
#Distance to core
plot(som_model, type = "quality", palette.name = coolBlueHotRed)
```

## Maps of the factors
```{r}
plot(som_model, type = "codes")
```

```{r}
par(mfrow = c(3, 3))
plot(som_model, type = "property", 
     property = som_model$codes[[1]][,1], 
     main = "age",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,2],
     main = "sex",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,3], 
     main = "income",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,4], 
     main = "married",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,5], 
     main = "children",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,6], 
     main = "car",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,7], 
     main = "mortgage",
     palette.name = coolBlueHotRed)

plot(som_model, type = "property", 
     property = som_model$codes[[1]][,8], 
     main = "delays",
     palette.name = coolBlueHotRed)
```

# Clusters description
```{r}
mydata <- as.matrix(som_model$codes[[1]])
#Use hierarchical clustering, k=3
som_cluster <- cutree(hclust(dist(mydata)), 3)
#Palette
pretty_palette <- c("#1f77b4", '#ff7f0e', '#2ca02c',
                    '#d62728', '#9467bd', '#8c564b', '#e377c2')
#Colored clusters
plot(som_model, type = "codes", 
     bgcol = pretty_palette[som_cluster])
add.cluster.boundaries(som_model, som_cluster) 
```

```{r}
aggregate(mydata,by=list(som_cluster),FUN=mean)
```