---
title: "NEURAL NETWORKS FOR CLASSIFICATION"
output:
  word_document: default
  html_notebook: default
  html_document: default
---

# Download the data and libraries
```{r}
library(dplyr)
library(nnet)
library(ggplot2)
library(knitr)
#setwd('D:/ML')
f <- read.csv('bank.csv', header = TRUE, encoding = 'UNICOD')
library (psych)
describe(f)
```

## Features Scaling
```{r}
f <- f[-1]
f$age = scale(f$age)
f$children = scale(f$children)
f$income = scale(f$income)
head(f)
```

## Splitting the scaled dataset into the TRAIN set and TEST set
```{r}
set.seed(123)
library(caTools)
split = sample.split(f$income, SplitRatio = 2/3)
f_train = subset(f, split == TRUE)
f_test = subset(f, split == FALSE)
```

# Fitting the NN
```{r results='hide'}
set.seed(11)
ff_cl <- nnet(data = f_train, delays ~ married + children + income + age, size = 3, maxit = 1000)
library(graphics)
source(file = 'plot.nnet.R')
plot.nnet(ff_cl)
```

## Predicting
```{r}
p_ff_cl <- predict(ff_cl, f_test, type = "class")
p <- as.factor(p_ff_cl)
```

## Confusion Matrix
```{r}
cm = table(f_test[, 'delays'], p)
print(cm)
```

# Fitting another ANN to the Training set
```{r}
# install.packages('h2o')
library(h2o)
h2o.init(nthreads = -1)
model = h2o.deeplearning(y = 'delays',
                         training_frame = as.h2o(training_set),
                         activation = 'Rectifier',
                         hidden = c(5,5),
                         epochs = 100,
                         train_samples_per_iteration = -2)
```

# Predicting the Test set results
```{r}
y_pred = h2o.predict(model, newdata = as.h2o(test_set[-11]))
y_pred = (y_pred > 0.5)
y_pred = as.vector(y_pred)
```

# Making the Confusion Matrix
```{r}
cm = table(test_set[, 11], y_pred)
```